name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3️⃣ Install dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install coverage

      # 4️⃣ Run tests with coverage
      - run: |
          coverage run -m unittest discover
          coverage xml

      # 5️⃣ Run SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: atik-foysal        # your SonarCloud org
          projectKey: sonar-python-sample  # your project key
          projectBaseDir: .
          extraProperties: |
            sonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

