name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage

      # 4️⃣ Run tests and generate coverage
      - name: Run tests with coverage
        run: |
          coverage run -m unittest discover
          coverage xml

      # 5️⃣ Install SonarQube Scanner
      - name: Install SonarQube Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.9.3.7196-linux.zip
          unzip sonar-scanner-cli-4.9.3.7196-linux.zip
          echo "${GITHUB_WORKSPACE}/sonar-scanner-4.9.3.7196-linux/bin" >> $GITHUB_PATH

      # 6️⃣ Run SonarQube Scanner
      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=sonar-python-sample \
            -Dsonar.organization=atik-foysal \
            -Dsonar.sources=. \
            -Dsonar.python.coverage.reportPaths=coverage.xml \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

